/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TanksRouteImport } from './routes/tanks'
import { Route as IndexRouteImport } from './routes/index'

const TanksRoute = TanksRouteImport.update({
  id: '/tanks',
  path: '/tanks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tanks': typeof TanksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tanks': typeof TanksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tanks': typeof TanksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tanks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tanks'
  id: '__root__' | '/' | '/tanks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TanksRoute: typeof TanksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanks': {
      id: '/tanks'
      path: '/tanks'
      fullPath: '/tanks'
      preLoaderRoute: typeof TanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TanksRoute: TanksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
